// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoCSHctNJt1In-kjYziw4ZQlBN2WBNPF4',
    appId: '1:843829452624:android:9560904942decd9e7e5655',
    messagingSenderId: '843829452624',
    projectId: 'chat-app-9a13c',
    storageBucket: 'chat-app-9a13c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkZl-6g07e7aYm06Ub1ttmSHyx3ieT-y0',
    appId: '1:843829452624:ios:cbb795b7a80fac4b7e5655',
    messagingSenderId: '843829452624',
    projectId: 'chat-app-9a13c',
    storageBucket: 'chat-app-9a13c.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  // يشترك macOS مع تطبيق iOS في Firebase لأنّ مُعرّف الحزمة واحد
  // (com.example.chatApp). إن سجّلت تطبيق macOS منفصلاً لاحقاً، أعد التوليد
  // عبر `flutterfire configure`.
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkZl-6g07e7aYm06Ub1ttmSHyx3ieT-y0',
    appId: '1:843829452624:ios:cbb795b7a80fac4b7e5655',
    messagingSenderId: '843829452624',
    projectId: 'chat-app-9a13c',
    storageBucket: 'chat-app-9a13c.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
